name: rine
version: 0.1.0.0
github: "SeedyROM/rine"
license: BSD3
author: "Zack Kollar"
maintainer: "me@seedyrom.io"
copyright: "2022 Zack Kollar"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/rine#readme>

dependencies:
  - base >= 4.7 && < 5
  - text
  - mtl
  - network
  - websockets
  - aeson
  - pipes
  - pipes-concurrency
  - stm
  - unix
  - hslogger
  - envy
  - lrucache

library:
  source-dirs: src
  ghc-options:
    - -Wall

executables:
  rine-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -O2
    dependencies:
      - rine

tests:
  rine-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - rine
